pipeline_engine: "nextflow"
input_files:
  - "samples/sample1.fastq"
  - "samples/sample2.fastq"

nextflow_workflow:
  script: "workflows/qc_pipeline.nf"
  workdir: "workdir"
  docker_image: "biocontainers/fastqc:latest"

qc_thresholds:
  mean_q30: 0.9
  dup_rate: 0.15
  align_rate: 0.85
